spring.application.name=Ecommerce
server.port=8080

spring.datasource.url=jdbc:mysql://127.0.0.1:3306/ecommerce_slim?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=dong2004!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
logging.level.org.springframework.security=DEBUG

# TẠM THỜI để chạy được ngay (tránh fail validate khi lệch schema)
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.physical_naming_strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.properties.hibernate.globally_quoted_identifiers=false
app.jwt.secret=6B4F8C8A9E7D4C2F1A3B5D7E9F1C3A5B7D9E1F2A3C4B5D6E7F8091A2B3C4D5E6

# Email configuration (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your-email@gmail.com
spring.mail.password=your-app-password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
app.email.from=your-email@gmail.com